server:
  port: 9999
camunda.bpm:
  admin-user:
    id: admin
    password: admin
    firstName: Demo
  filter:
    create: All tasks
spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect